# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
osx_image: xcode7
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
  matrix:
    - DESTINATION="OS=8.1,name=iPhone 4S" SCHEME="Swinject-iOS" SDK=iphonesimulator9.0 POD_LINT="NO" ACTION="test"
#    - DESTINATION="OS=8.2,name=iPhone 5" SCHEME="Swinject-iOS" SDK=iphonesimulator9.0 POD_LINT="NO" ACTION="test"
#    - DESTINATION="OS=8.3,name=iPhone 5S" SCHEME="Swinject-iOS" SDK=iphonesimulator9.0 POD_LINT="NO" ACTION="test"
#    - DESTINATION="OS=8.4,name=iPhone 6" SCHEME="Swinject-iOS" SDK=iphonesimulator9.0 POD_LINT="NO" ACTION="test"
    - DESTINATION="OS=9.0,name=iPhone 6 Plus" SCHEME="Swinject-iOS" SDK=iphonesimulator9.0 POD_LINT="YES" ACTION="test"
    - DESTINATION="arch=x86_64" SCHEME="Swinject-OSX" SDK=macosx10.11 POD_LINT="NO" ACTION="test"
    - DESTINATION="OS=2.0,name=Apple Watch - 42mm" SCHEME="Swinject-watchOS" SDK=watchsimulator2.0 POD_LINT="NO" ACTION="build"
before_install:
  - curl -L -O https://github.com/Carthage/Carthage/releases/download/0.9.2/Carthage.pkg
  - sudo installer -pkg Carthage.pkg -target /
  - carthage version
  - carthage bootstrap --verbose --no-use-binaries --use-submodules
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -project Swinject.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" 
    -configuration Debug ONLY_ACTIVE_ARCH=NO $ACTION | xcpretty -c
  - xcodebuild -project Swinject.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" 
    -configuration TestableRelease ONLY_ACTIVE_ARCH=NO $ACTION | xcpretty -c
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint --quick;
    fi
notifications:
  email:
    on_success: never
